[tool.pytest.ini_options]
testpaths  = ["tests/python"]
pythonpath = ["python"]
addopts    = "-p no:cov -p no:xdist --timeout=2 --maxfail=2"

[tool.flake8]
max-line-length = 100

[tool.black]
line-length = 100
